# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Geoh5py
author: Mira Geoscience Ltd.
copyright: "2025"
logo: images/geoh5py_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  run_in_temp: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinx.ext.todo
    - sphinx_issues
    - sphinxcontrib.googleanalytics
    #- sphinx.ext.autosummary  # TODO: restore? for now, tons of error
    #- sphinx.ext.viewcode  # TODO: restore? for now, tons of error
  local_extensions:
    dynamic_config: _ext/
  recursive_update: true
  config:
    project: geoh5py
    html_static_path:
      - _static/custom.css
    html_theme: alabaster
    autodoc_typehints: signature
    autodoc_typehints_format: short
    suppress_warnings:
      - etoc.toctree
    intersphinx_mapping:
      # use None to autoâ€‘fetch objects.inv
      numpy:
        - https://numpy.org/doc/1.26/
        - null
      python:
        - https://docs.python.org/3/
        - null
    todo_include_todos: true
    issues_github_path: mirageoscience/geoh5py
    autodoc_type_aliases:
      np.ndarray: numpy.ndarray
      UUID: uuid.UUID

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
