name: geoh5py_docs

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pydantic
  - matplotlib
  - scipy
  - numpy
  - h5py
  - pip
  - jupyter-book=1.0
  - jupytext
  - notebook
  - pip:
    - sphinx
    - sphinx_issues
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - sphinxcontrib-googleanalytics
    - nbsphinx
    - nbstripout
    - numpydoc
    - jupyter_client
